In [2]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import duckdb as db
from datasets import load_dataset
from dotenv import load_dotenv

In [3]:
%matplotlib inline

In [16]:
# 1. Load the hidden variables from your .env file
load_dotenv()

# 2. Grab the token securely
my_token = os.getenv("HF_TOKEN")

# 3. Pass the token into the load_dataset function
dataset = load_dataset(
    "foursquare/fsq-os-places",
    split="train",
    token=my_token
)

Resolving data files:   0%|          | 0/100 [00:00<?, ?it/s]

Resolving data files:   0%|          | 0/100 [00:00<?, ?it/s]

Downloading data:   0%|          | 0/100 [00:00<?, ?files/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/126M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/99.1M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/131M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/124M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/119M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/119M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/119M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/111M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/111M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/121M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/115M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/127M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/111M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/109M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/106M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/110M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/106M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/121M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/103M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/121M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/135M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/99.7M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/102M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/109M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/113M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/99.2M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/95.5M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/98.9M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/96.9M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/99.8M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/84.6M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/97.5M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/94.2M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/102M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/106M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/109M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/98.3M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/107M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/100M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/110M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/115M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/111M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/110M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/103M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/109M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/102M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/102M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/118M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/107M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/122M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/111M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/131M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/115M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/120M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/133M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/128M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/126M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/129M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/123M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/112M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/116M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/124M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/123M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/138M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/131M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/123M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/132M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/122M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/117M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/108M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/106M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/106M [00:00<?, ?B/s]

release/dt=2026-04-14/places/parquet/pla(…):   0%|          | 0.00/114M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/107502541 [00:00<?, ? examples/s]

Loading dataset shards:   0%|          | 0/90 [00:00<?, ?it/s]

In [17]:
# Export the entire dataset straight to a local Parquet file
dataset.to_parquet("all_foursquare_locations.parquet")

Creating parquet from Arrow format:   0%|          | 0/474 [00:00<?, ?ba/s]

47312790141

In [4]:
# Query the entire global dataset
sql_query = """
    SELECT COUNT(*) AS num_rows 
    FROM 'all_foursquare_locations.parquet';
"""

results = db.query(sql_query).df()
display(results)

    num_rows
0  107502541

In [4]:
# Query the entire global dataset
sql_query = """
    SELECT * 
    FROM 'all_foursquare_locations.parquet'
    WHERE country = 'AU';
"""

results = db.query(sql_query).df()

In [20]:
# Save the filtered Australian locations to a compressed Parquet file
results.to_parquet('au_locations.parquet', index=False)

In [12]:
# Display all states in AUS
sql_query = """
    SELECT name, latitude, longitude, address, locality, region, date_closed, tel, website, email, fsq_category_labels
    FROM 'au_locations.parquet'
"""

aus_results = db.query(sql_query).df()
display(aus_results)

,name,latitude,longitude,address,locality,region,date_closed,tel,website,email,fsq_category_labels
0,Nailtazia Nails Beauty,NaN,NaN,Unit 5 Cnr Vansittart Rd & Mt Lindsay Hwy,Regents Park,QLD,NaN,(07) 3800 5066,NaN,NaN,[Business and Professional Services > Health a...
1,Regus,NaN,NaN,40 City Rd Level 23,Melbourne,VIC,NaN,(03) 9674 0444,https://www.regus.com/en-gb/australia/melbourn...,NaN,[Business and Professional Services > Office >...
2,Miss Maud Swedish Pastry Houses,NaN,NaN,"Great Eastern Hwy, Midland Gate Shopping Centr...",Midland,WA,NaN,NaN,http://www.missmaud.com.au,NaN,"[Dining and Drinking > Cafe, Coffee, and Tea H..."
3,Outdoor Furniture Online,NaN,NaN,11 Villiers Dr Unit 4,Currumbin,QLD,NaN,(07) 5521 0550,http://www.outdoorfurnitureonline.com.au,NaN,[Retail > Furniture and Home Store]
4,AF Antique Restorations,NaN,NaN,100 Canterbury Rd,Camberwell,VIC,NaN,(03) 9836 1446,NaN,NaN,<NA>
...,...,...,...,...,...,...,...,...,...,...,...
1496347,Jetty,-31.523158,159.058579,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,"[Travel and Transportation > Pier, Travel and ..."
1496348,Benny’s Fish Truck,-31.523349,159.058850,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,[Dining and Drinking > Restaurant > Fish and C...
1496349,Mount Eliza,-31.513594,159.040227,NaN,Lord Howe Island,NSW,NaN,(03) 9349 8788,NaN,NaN,[Landmarks and Outdoors > Mountain]
1496350,North Beach,-31.517629,159.043549,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,[Landmarks and Outdoors > Beach]
1496351,Ball's Pyramid,-31.754372,159.251568,NaN,Lord Howe Island,Lord Howe Island,NaN,NaN,NaN,NaN,[Landmarks and Outdoors > Island]

In [20]:
# Display CLEANED set via state
state = input("State ('all' for all states): ").lower()

if state == "all":
    sql_query = """
        SELECT name, latitude, longitude, address, locality, region, date_closed, tel, website, email, fsq_category_labels
        FROM 'au_locations.parquet'
        WHERE latitude IS NOT NULL AND longitude IS NOT NULL
    """
else:
    sql_query = f"""
        SELECT name, latitude, longitude, address, locality, region, date_closed, tel, website, email, fsq_category_labels
        FROM 'au_locations.parquet'
        WHERE LOWER(region) = '{state}' AND latitude IS NOT NULL AND longitude IS NOT NULL
    """

aus_results = db.query(sql_query).df()
display(aus_results)

State ('all' for all states):  nsw

,name,latitude,longitude,address,locality,region,date_closed,tel,website,email,fsq_category_labels
0,Ananda Wellness Retreat Jamberoo,-43.529603,146.528046,406 Jamberoo Mountain Rd,Jamberoo,NSW,NaN,(02) 4236 0269,https://www.yalwa.com.au/Yoga/31073,NaN,[Sports and Recreation > Gym and Studio > Yoga...
1,Sandy Bay,-42.909632,147.349383,Sandy Bay Rd,Clontarf,NSW,NaN,NaN,NaN,NaN,[Landmarks and Outdoors > Park > Dog Park]
2,Findon Creek Cottage,-42.887259,147.811628,38 Bendalls Rd,Findon Creek,NSW,NaN,(02) 6636 4294,http://findoncreekcottage.com,NaN,"[Travel and Transportation > Lodging > Hotel, ..."
3,Richmond Christmas Tree Farm,-42.693843,147.472338,364 Fingerpost Rd,Richmond,NSW,NaN,0488 226 232,http://richmondchristmastreefarm.com.au,NaN,<NA>
4,Bridge Street Cafe,-42.735022,147.438202,39 Bridge St,Richmond,NSW,NaN,(03) 6260 2187,NaN,NaN,"[Dining and Drinking > Cafe, Coffee, and Tea H..."
...,...,...,...,...,...,...,...,...,...,...,...
446900,Ocean View Apartments,-31.522670,159.059519,Ocean View Dr,Lord Howe Island,NSW,NaN,(02) 6563 2041,https://oceanviewlordhoweisland.com.au,NaN,[Travel and Transportation > Lodging > Resort]
446901,Jetty,-31.523158,159.058579,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,"[Travel and Transportation > Pier, Travel and ..."
446902,Benny’s Fish Truck,-31.523349,159.058850,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,[Dining and Drinking > Restaurant > Fish and C...
446903,Mount Eliza,-31.513594,159.040227,NaN,Lord Howe Island,NSW,NaN,(03) 9349 8788,NaN,NaN,[Landmarks and Outdoors > Mountain]
446904,North Beach,-31.517629,159.043549,NaN,Lord Howe Island,NSW,NaN,NaN,NaN,NaN,[Landmarks and Outdoors > Beach]